### ISSUE TITLE
missing requirement

### ISSUE THREAD

**Issue by JarbasAl** [MycroftAI/skill-volume#62]
This happened to me when upgrading to ubuntu 20, it didnt happen before so i think this package used to be installed by default

adding pyalsaaudio to requirements.txt should fix it

Logs bellow from a mint install, see https://github.com/MycroftAI/mycroft-core/issues/2609#issuecomment-640141520
```
 04:17:55.874 | ERROR    | 15570 | mycroft.skills.skill_loader:_load_skill_source:215 | Failed to load skill: mycroft-volume.mycroftai (ModuleNotFoundError("No module named 'alsaaudio'",))
Traceback (most recent call last):
  File "/home/florin/snap/mycroft/common/venv/lib/python3.6/site-packages/mycroft/skills/skill_loader.py", line 208, in _load_skill_source
    ('.py', 'rb', imp.PY_SOURCE)
  File "/snap/mycroft/current/usr/lib/python3.6/imp.py", line 235, in load_module
    return load_source(name, filename, file)
  File "/snap/mycroft/current/usr/lib/python3.6/imp.py", line 172, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 684, in _load
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/florin/snap/mycroft/1078/../common/mycroft-data/skills/mycroft-volume.mycroftai/__init__.py", line 15, in <module>
    from alsaaudio import Mixer, mixers as alsa_mixers
ModuleNotFoundError: No module named 'alsaaudio'
```

python version does not seem relevant, i can replicate using python 3.8, logs above indicate python 3.6

**Comment by forslund** [comment]
Great catch Jarbas, this should indeed require pyalsaaudio. Could have sworn it was added here when it was made an optional install for mycroft-core

Edit: Had it as a local change but not committed.
